/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module "vue" {
  export interface GlobalComponents {
    BaseTable: typeof import("./../src/components/BaseTable/index.vue")["default"];
    BaseTableColumn: typeof import("./../src/components/BaseTable/BaseTableColumn.vue")["default"];
    BaseTablePage: typeof import("./../src/components/BaseTablePage/index.vue")["default"];
    EditCell: typeof import("./../src/components/EditCell/index.vue")["default"];
    ElBreadcrumb: typeof import("element-plus/es")["ElBreadcrumb"];
    ElBreadcrumbItem: typeof import("element-plus/es")["ElBreadcrumbItem"];
    ElButton: typeof import("element-plus/es")["ElButton"];
    ElCheckbox: typeof import("element-plus/es")["ElCheckbox"];
    ElCheckboxGroup: typeof import("element-plus/es")["ElCheckboxGroup"];
    ElConfigProvider: typeof import("element-plus/es")["ElConfigProvider"];
    ElDatePicker: typeof import("element-plus/es")["ElDatePicker"];
    ElForm: typeof import("element-plus/es")["ElForm"];
    ElFormItem: typeof import("element-plus/es")["ElFormItem"];
    ElIcon: typeof import("element-plus/es")["ElIcon"];
    ElInput: typeof import("element-plus/es")["ElInput"];
    ElMenu: typeof import("element-plus/es")["ElMenu"];
    ElMenuItem: typeof import("element-plus/es")["ElMenuItem"];
    ElPagination: typeof import("element-plus/es")["ElPagination"];
    ElPopover: typeof import("element-plus/es")["ElPopover"];
    ElSubMenu: typeof import("element-plus/es")["ElSubMenu"];
    ElTableColumn: typeof import("element-plus/es")["ElTableColumn"];
    HeaderFilter: typeof import("./../src/components/BaseTable/HeaderFilter.vue")["default"];
    IconSvgClassify: typeof import("~icons/svg/classify.svg")["default"];
    IconSvgFilter: typeof import("~icons/svg/filter.svg")["default"];
    IconSvgLogout: typeof import("~icons/svg/logout.svg")["default"];
    IconSvgRefresh: typeof import("~icons/svg/refresh.svg")["default"];
    IconSvgSort: typeof import("~icons/svg/sort.svg")["default"];
    IconSvgSwitch: typeof import("~icons/svg/switch.svg")["default"];
    IconSvgSwitchLang: typeof import("~icons/svg/switch-lang.svg")["default"];
    IconSvgUser: typeof import("~icons/svg/user.svg")["default"];
    IconTitle: typeof import("./../src/components/IconTitle/index.vue")["default"];
    PlanDrawer: typeof import("./../src/components/PlanDrawer/index.vue")["default"];
    PlanSelect: typeof import("./../src/components/PlanSelect/index.vue")["default"];
    PlanTable: typeof import("./../src/components/PlanTable/index.vue")["default"];
    PlanTimeline: typeof import("./../src/components/PlanTimeline/index.vue")["default"];
    PlanUpload: typeof import("./../src/components/PlanUpload/index.vue")["default"];
    RouterLink: typeof import("vue-router")["RouterLink"];
    RouterView: typeof import("vue-router")["RouterView"];
    SelectCell: typeof import("./../src/components/SelectCell/index.vue")["default"];
  }
}
